### ISSUE TITLE
WorkflowService interface leaks internal WorkflowService.replace function

### ISSUE THREAD

**Issue by masinger** [lisegmbh/fluxflow#10]
The WorkflowService interface declares a .replace function which is used internally whenever a workflow should be replaced.

It is
* leaking internal functionality
* not clearly documented
* possibly missing the deletion/cancellation of scheduled jobs 

It should therefore be refactored.

**Comment by masinger** [comment]
Best would be to deprecate the interface method and remove it in an upcoming version.

**Comment by masinger** [comment]
@bobmazy Can you remember why this function has been added?

Currently the difference between `delete` and `replace` is, that replace doesn't:
- load the workflow to be deleted
- delete jobs
- publish the `WorkflowDeletedEvent`

I understand why one wouldn't want to publish the event. But do you know why jobs are not deleted?

```kotlin
    override fun delete(identifierToDelete: WorkflowIdentifier) {
        val workflowToDelete = persistence.find(identifierToDelete)
            ?: throw WorkflowNotFoundException(identifierToDelete)

        persistence.delete(identifierToDelete)
        stepService.deleteAllForWorkflow(identifierToDelete)
        jobService.deleteAllForWorkflow(identifierToDelete)

        eventService.publish(
            WorkflowDeletedEvent(
                WorkflowImpl<Any>(workflowToDelete)
            )
        )
    }

    override fun replace(identifierToDelete: WorkflowIdentifier) {
        persistence.delete(identifierToDelete)
        stepService.deleteAllForWorkflow(identifierToDelete)
    }
```

**Comment by bobmazy** [comment]
@masinger 
We had to dynamically adjust the type of the workflow model, which previously could only be done by starting a new workflow and deleting the current one. This also resulted in a new workflow identifier being assigned, which we did not want. 
Therefore, we added the replace method to keep the workflow identifier and be able to change the type of the workflow model.

**Comment by masinger** [comment]
> @masinger 
> 
> We had to dynamically adjust the type of the workflow model, which previously could only be done by starting a new workflow and deleting the current one. This also resulted in a new workflow identifier being assigned, which we did not want. 
> 
> Therefore, we added the replace method to keep the workflow identifier and be able to change the type of the workflow model.

Yeah, I know about the reason/need for the "replace functionality". But I am wondering why the implementation would need a dedicated Workflow.replace functionality, which deletes everything (like Workflow.remove) except jobs?
