### ISSUE TITLE
Step/Workflow state is not persisted before publishing the step data events

### ISSUE THREAD

**Issue by masinger** [lisegmbh/fluxflow#47]
When step data is updated, the step data event is currently published before actually persisting the updated step data.

This will cause listeners to read stale workflow information when querying for information regarding the affected workflow/step/data.

**Comment by masinger** [comment]
Currently the order of operation (see `StepDataService 37:69`) is:

1. Set the new data value
2. Invoke all update listeners
3. Execute continuations returned by update listeners (if any)
4. Publish StepDataEvent
5. Persist changes

As Events are intended to notify "external logic" about changes to the workflow, it can be argued that
- the workflow should be in a stable state whenever such events are published
- such external listeners should not expect their changes to be persisted implicitly

**The fixed order of operation could be**
1. Set the new data value
2. Invoke all update listeners
3. Execute continuations returned by update listeners (if any)
4. Persist changes
5. Publish StepDataEvent

Nevertheless, I am wondering why the original implementation was done this way? @bobmazy @DerPipo

**Comment by bobmazy** [comment]
I also don't know why the event is published before it's saved. I see no reason why this should not be changed.

(I think you mean the `StepDataServiceImpl` class in the code reference and not the `StepDataService` interface)

**Comment by masinger** [comment]
I've taken a look into the old repository and it looks like the publishing action has been moved there intentionally. According to the commit, it has explicitly been done to allow listeners to update the workflow without having to persist changes themself.

> Commit: 27e3bdc8165ebf5416dccec3fa1937e6de0cb7af
> Author: Marcel Singer <marcel.singer@lise.de>
> Publish data and action events before persisting the workflow, so listeners may modify workflow information

<img src="https://i.redd.it/gcuzho5q48h81.png" width="300" />

Nevertheless, I would stick to the previous agreement:

> External event listeners should not expect their changes to be persisted implicitly/automatically.
