### ISSUE TITLE
Extend @DisplayName Annotation to StepData

### ISSUE THREAD

**Issue by bobmazy** [lisegmbh/fluxflow#50]
At present, we have the functionality to add `@DisplayName` annotations to Steps and StepActions.

It would be beneficial if we could extend the use of `@DisplayName` annotations to StepData as well. This would make it possible to add a meaningful display name to class properties.

### Proposed solution
Similar to how we store the `@DisplayName` for Steps, the display name could be stored in the StepData class property `metadata`.

**Comment by masinger** [comment]
Good point, but note that the `@DisplayName` annotation is not a FluxFlow type. It just an annotation in our third-party project, that utilized the current metadata feature available for steps and their actions.

**Comment by masinger** [comment]
@bobmazy Are you still working on this feature?

**Comment by bobmazy** [comment]
> @bobmazy Are you still working on this feature?

No, not yet
