### ISSUE TITLE
Configurable replacement scope for `Continuation.workflow(..., forkBehavior = ForkBehavior.Replace)` continuations

### ISSUE THREAD

**Issue by masinger** [lisegmbh/fluxflow#99]
**Current situation**
When a workflow is replaced by returning a continuation with `forkBehavior` set to `ForkBehavior.Replace`, the workflow engine removes the old workflow state as well as all old steps. The only elements that aren't removed, are jobs and continuation records.

This behavior might at least be surprising or even problematic if jobs are relying on the "original" workflow model.

**Proposed solution**
1. WorkflowContinuation should be extend with an optional `replacementScope`
2. The property states which workflow objects belonging to the old workflow should be replaced/removed
3. The `WorkflowService.removeSilently` function accepts this as a parameter and only removes the specified workflow elements

Relates to #10.

**Comment by bobmazy** [comment]
@masinger 
What should be the new default value of the replacement scope? Or should the user be forced to pass a replacement scope when using the replace fork behaviour for a workflow continuation?

See my draft PR #141 
There I set the default value to empty (and only the workflow itself is deleted).

**Comment by masinger** [comment]
@bobmazy Sorry for the late reply - I seem to have missed the Github notification(s).

Having a now empty replacement scope would be a breaking change when compared to the previous behavior of deleting steps and jobs. Normally I would suggest that the default should remain being [Step, Job] in order to avoid having a breaking change, that might go unnoticed (as it is only a breaking change in behavior and not noticeable during compilation). But on the other hand, having and empty default is the far more reasonable option.

All points considered, I would suggest going with an empty default because this is the "more correct" default and there are not a lot of dependent project that might be affected by the breaking change. Additionally FluxFlow's API is still be considered unstable (`0.X.X`) and allows us to have breaking changes.
